# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
