# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170327_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='caseid',
        ),
        migrations.AddField(
            model_name='user',
            name='myplan',
            field=models.ManyToManyField(related_name='_user_myplan_+', to='blog.Plan'),
        ),
    ]
