# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170327_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
