# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170331_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
