# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170331_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myarticle',
            field=models.ManyToManyField(related_name='_user_myarticle_+', to='blog.Plan'),
        ),
    ]
