# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170331_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
