# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170401_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='day',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
    ]
