# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170402_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plantype',
            field=models.CharField(choices=[('plan', '\u884c\u7a0b'), ('article', '\u6e38\u8bb0')], default='plan', max_length=10),
        ),
    ]
